# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hover < Formula
  desc "A CLI for deploying web applications to AWS Lambda"
  homepage "https://github.com/themsaid/hover"
  version "0.0.4"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/themsaid/hover/releases/download/v0.0.4/hover_0.0.4_Darwin_arm64.tar.gz"
      sha256 "9bb839f64ec86260d621460a602350733a346b2a902d1899bbedf2a4b8bad9aa"

      def install
        bin.install "hover"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/themsaid/hover/releases/download/v0.0.4/hover_0.0.4_Darwin_amd64.tar.gz"
      sha256 "89850a2434c8195ea2de4f0b5bbb3033d64e1f2fb83f02916e4d390de98531ae"

      def install
        bin.install "hover"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/themsaid/hover/releases/download/v0.0.4/hover_0.0.4_Linux_arm64.tar.gz"
      sha256 "6268e0d3f5998020165488c31ca69e0f4cc169e425ebadfea3e0627078988f14"

      def install
        bin.install "hover"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/themsaid/hover/releases/download/v0.0.4/hover_0.0.4_Linux_amd64.tar.gz"
      sha256 "ffa7473cc40aa9db61a610777bf88a937582933dc57d2edf0254442262a8fc04"

      def install
        bin.install "hover"
      end
    end
  end
end
